name: client
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04 #배포 실행될 환경
    steps: #각 단계의 이름과 실행내용을 나열해서 작성한다.
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules # 빌드시 캐시 설정
        uses: actions/cache@v3
        with:
          path: ./fe/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm install
        working-directory: ./fe #디렉토리명

      - name: Build
        run: npm run build
        working-directory: ./fe
        env:
          REACT_APP_EC2_SERVER: ${{ secrets.REACT_APP_EC2_SERVER }}

      - name: SHOW AWS CLI VERSION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://codesquad-2024-team8-issue-tracker \
            --delete
        working-directory: ./fe

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}} --paths "/*"
