name: client
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04 #배포 실행될 환경
    steps: #각 단계의 이름과 실행내용을 나열해서 작성한다.
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "20"
        run: npm install
        working-directory: ./fe #디렉토리명

      - name: Build
        run: npm run build
        working-directory: ./fe

      - name: SHOW AWS CLI VERSION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://codesquad-2024-team8-issue-tracker \
            --delete
        working-directory: ./fe
